### PR TITLE
Add Simplified Chinese (zh_CN) translation.

### PR DESCRIPTION
**Pull request by Geno1024**
This is my ~~WIP~~updated to the 3.6 translation in Simplified Chinese (zh_CN) for WhatPulse.

It's my pleasure for contributing to this project.
I am coming from the "What's New" in 3.5, but I didn't receive a reply from sending a email for requesting the way of contributing translations (maybe in trashbin?), then I searched in Help Center and found here.

I am inside a company which technically denies employees from pushing to GitHub due to security reasons, so I have to use a mobile phone for translating.
Slow, but keep going.

There are 936 messages to translate. (`grep -c "<source>" whatpulse.ts.template`)

### CODE REVIEW

**Comment by Geno1024** [comment]
And a question:

How should I rename this file for Qt? In which language code?
Chinese language has several "variant"s. As per POSIX Locale "Standard", there are at least `zh_CN` (Simplified Chinese for Mainland China), `zh_HK` (Traditional Chinese for Hongkong, China), `zh_SG` (Simplified(? I am not so sure) Chinese for Singapore), `zh_TW` (Traditional Chinese for Taiwan, China).
Now I am just contributing to `zh_CN`, and there maybe other WhatPulse users who will contribute to other "variant"s. How should I name this file according to the conventions of Qt?

**Comment by Geno1024** [comment]
> And a question:
> 
> How should I rename this file for Qt? In which language code?

LOL. Sorry for didn't [RTFM](https://doc.qt.io/qt-5/linguist-translators.html#changing-the-target-locale). My rename was correct.

**Comment by smitmartijn** [comment]
Hi @Geno1024,

If it's easier - you can also translate the file and then send it to martijn@whatpulse.org and I'll add it to Github. I think the reply-to for newsletters is set to a no-reply address, so glad you found the help center article. 😄

**Comment by Geno1024** [comment]
Now all translate finished. But some questions remains due to different word sequence between English and Chinese.

For example, "Auto pulse on 50000 keys" is more usually translated as "在 50000 按键时自动 Pulse" (literally, at 50000 keys auto pulse) in Chinese, that's my handling in that page: Translate "Auto pulse on" -> "在", "keys" -> "按键时自动 Pulse", which will made the sequence seems fit into Chinese grammar in the software presentation and concatenation (however there may be some layout issues).

But the "Auto pulse on hour 0 on every day" is hard to compat between grammar and layout, and the handling is very hard at "WhatPulse will automatically pulse when ...".

I hope my sentence concatenation and handling is correct.

**Comment by Geno1024** [comment]
And, I keep "WhatPulse", "Pulse", and some key names not translated.

**Comment by smitmartijn** [comment]
Looks great, thanks!

**Comment by Geno1024** [comment]
Thank you! I am waiting for the next version, to fine-tune the translations.

**Pull request merged**
