### PR TITLE
Slovak translation updates

### PR DESCRIPTION
**Pull request by TheMorc**
Another set of updates. Hopefully without any apparent mistakes 🙃, probably would be a better idea to wait until you update the client so I can check if it's all correct.

### CODE REVIEW

**Comment by smitmartijn** [comment]
Hey @TheMorc  - apologies about the timing, but it seems you submitted this right in between I was doing some major overhauls, and there's conflicts now. Looking at your changes, it feels good to see a lot of your changes already reflected in the automatic translations I'm doing now.

I switched to using GPT to update the translations, which has a lot more context around WhatPulse in general, meaning the quality is way better than before (I was using DeepL and Google Translate).

If it's not too much trouble, can you rebase on the current branch and see if you'd like to change anything more?

**Comment by TheMorc** [comment]
That's cool to see actually. And no problems with that, I'll see what I can do

**Comment by TheMorc** [comment]
Those translations are spot on. Some of them are better than mine, some of them needed some slight modifications but overall, it's really nice! 
There's still that encoding fight though, `&quot;` changing to `"` and back and forth.

**Comment by smitmartijn** [comment]
Awesome to hear 😊 The encoding thing is annoying, but I've tested the difference fully now, and it doesn't seem to make an impact - the client still picks up everything. I think Qt started to use HTML encoding in a recent version, but it's backwards compatible, so all good. I'll transition all of the files to use the tags.

**Pull request merged**
